---
title: "Planificación"
toc: false
page-layout: full
execute:
  freeze: auto 
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```


<br>

<table style="width:100%; border-spacing: 0 12px; font-size: 16px;">
  <thead>
      <th style="padding: 14px;"></th>
      <th style="padding: 14px;"><i class="fas fa-chalkboard-teacher"></i> Clases</th>
      <th style="padding: 14px;"><i class="fas fa-user-edit"></i> Talleres</th>
      <th style="padding: 14px;"><i class="fas fa-book-reader"></i> Lecturas</th>
    </tr>
  </thead>
  <tbody>
    <!-- UNIDAD 1 -->
    <tr><td colspan="4" style="padding: 14px; font-size: 22px;"><strong> UNIDAD 1: <i> Introducción </i> </strong></td></tr>
    <tr><td style="padding: 20px;"><span style="color: orange;"><strong>Agosto</strong></span></td><td></td><td></td><td></td></tr>
    <tr>
      <td style="padding: 14px;">Martes 4</td>
      <td style="padding: 14px;"><a>Presentación del curso</a></td>
      <td style="padding: 14px;"></td>
    </tr>
    <tr>
      <td style="padding: 14px;">Martes 11</td>
      <td style="padding: 14px;"><a>¿Qué es el feminismo de datos?</a></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"><a href="/files/textos/Desrosieres.pdf">@dignazio1CapituloPoder2023</a> Leer cap. 8</td>
    </tr>
    <!-- UNIDAD 2 -->
    <tr><td colspan="4" style="padding: 14px; font-size: 22px;"><strong>UNIDAD 2: <i>Diseños de investigación social cuantitativa</i> </strong></td></tr>
    <tr>
      <td style="padding: 14px;">Martes 19</td>
      <td style="padding: 14px;"><a href="/content/02-content.html">Diseños de investigación</a></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"><a href="/files/textos/Hernandez.pdf">Hernández, Fernández & Baptista</a> Leer cap. 7</td>
    </tr>
    <tr style="background-color: #e0e0e0;">
      <td style="padding: 14px;">Martes 26</td>
      <td style="padding: 14px;"><b>Suspendida</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <!-- UNIDAD 3 -->
    <tr><td colspan="4" style="padding: 14px; font-size: 22px;"><strong> UNIDAD 3: <i>Conceptos y medición</i></strong></td></tr>
    <tr><td style="padding: 20px;"><span style="color: orange;"><strong>Septiembre</strong></span></td><td></td><td></td><td></td></tr>
    <tr>
      <td style="padding: 14px;">Martes 2</td>
      <td style="padding: 14px;"><a href="/content/05-content.html"> Tipos de variables, indicadores directos e indirectos, indicadores sociales</a></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"><a href="/files/textos/Gavarotto.pdf">Gavarotto</a></td>
    </tr>
    <tr>
      <td style="padding: 14px;">Martes 9</td>
      <td style="padding: 14px;"><a href="/content/06-content.html"> </a></td>
      <td style="padding: 14px;"><a href="/assignment/01-assignment.html">Taller de operacionalización</a></td>
      <td style="padding: 14px;"><a href="/files/textos/Hernandez.pdf">Hernández, Fernández & Baptista</a>  Leer cap. 9</td>
    </tr>
    <tr style="background-color: #e0e0e0;">
      <td style="padding: 14px;">Martes 16</td>
      <td style="padding: 14px;"><b>Pausa</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <tr>
        </tr>
    <tr style="background-color: #F2DFCD;">
      <td style="padding: 14px;">Martes 23</td>
      <td style="padding: 14px;"><b>Prueba I</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
      <tr>
      <td style="padding: 14px;">Martes 30</td>
      <td style="padding: 14px;"><a href="/content/06-content.html"> </a></td>
      <td style="padding: 14px;"><a href="/assignment/01-assignment.html">Taller de operacionalización</a></td>
    </tr>
    <!-- UNIDAD 4 -->
    <tr><td colspan="4" style="padding: 14px; font-size: 22px;"><strong> UNIDAD 4: <i>Construcción de índices y escalas</i>
</strong></td></tr>
    <tr><td style="padding:20px;"><span style="color: orange;"><strong>Octubre</strong></span></td><td></td><td></td><td></td></tr>
    <tr>
      <td style="padding: 14px;">Martes 7</td>
      <td style="padding: 14px;"><a href="/content/08-content.html">Construcción de índices</a></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"><a href="/files/textos/Asun.pdf">Asún</a> Leer Construcción de cuestionarios y escalas</td>
    </tr>
      </tr>
    <tr style="background-color: #F2DFCD;">
      <td style="padding: 14px;">Martes 14</td>
      <td style="padding: 14px;"><b>Prueba II</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <tr>
      <tr>
      <td style="padding: 14px;">Martes 21</td>
      <td style="padding: 14px;"><a href="/content/09-content.hmtl">Construcción de escalas</a></td>
      <td style="padding: 14px;"><a>Taller de índices y escalas*</a></td>
      <td style="padding: 14px;"><a href="/files/textos/Tanujaya.pdf">Tanujaya, Prahmana & Mumu</a></td>
    </tr>
    <tr style="background-color: #e0e0e0;">
      <td style="padding: 14px;">Martes 28</td>
      <td style="padding: 14px;"><b>Pausa</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <!-- UNIDAD 5 -->
    <tr><td colspan="4" style="padding: 14px; font-size: 22px;"><strong> UNIDAD 5: <i>La técnica de la encuesta social</i>
</strong></td></tr>
    <tr><td style="padding: 20px;"><span style="color: orange;"><strong>Noviembre</strong></span></td><td></td><td></td><td></td></tr>
    <tr>
      <td style="padding: 14px;">Martes 4</td>
      <td style="padding: 14px;"><a href="/content/10-content.html">Introducción a la encuesta</a></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"><a href="/files/textos/Einola.pdf">Einola & Alvesson</a></td>
    </tr>
    <tr style="background-color: #F2DFCD;">
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"><b>Entrega trabajo I</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <tr>
      <td style="padding: 14px;">Martes 11</td>
      <td style="padding: 14px;"><a href="/content/11-content.html">Evaluación crítica de encuestas sociales</a></td>
      <td style="padding: 14px;"><a href="/assignment/04-assignment.html">Taller de cuestionarios</a></td>
      <td style="padding: 14px;"><a href="/files/textos/Villarroel.pdf">Villarroel</a></td>
    </tr>
    <tr>
      <td style="padding: 14px;">Martes 18</td>
      <td style="padding: 14px;"><a href="/content/10-content.html">Introducción al muestreo</a></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <tr style="background-color: #F2DFCD;">
      <td style="padding: 14px;">Martes 25</td>
      <td style="padding: 14px;"><b>Entrega trabajo II</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <tr><td style="padding: 20px;"><span style="color: orange;"><strong>Diciembre</strong></span></td><td></td><td></td><td></td></tr>
    <tr style="background-color: #e0e0e0;">
      <td style="padding: 14px;">Martes 2</td>
      <td style="padding: 14px;"><b>Exámenes</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
    <tr style="background-color: #e0e0e0;">
      <td style="padding: 14px;">Martes 11</td>
      <td style="padding: 14px;"><b>Exámenes</b></td>
      <td style="padding: 14px;"></td>
      <td style="padding: 14px;"></td>
    </tr>
  </tbody>
</table>



                       
<br>

## Exámenes finales (escritos)

Ver [requisitos de aprobación y eximición](https://cuantitativa.netlify.app/syllabus#requisitos-de-aprobaci%C3%B3n)

-   Examen de primera oportunidad: ***próximamente...*** 

-   Examen de segunda oportunidad: ***próximamente...***
